# Generated by Django 4.0.4 on 2022-04-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(blank=True, null=True, verbose_name='Ordered date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Order accepted'), ('C', 'Carried out'), ('F', 'Order finished')], default='A', help_text='Status', max_length=1),
        ),
    ]
