# Generated by Django 4.0.4 on 2022-04-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
